/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/fs/dirs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A directory's immediate subdirectories, or the roots to start from.
         * @description Exposes the machine's directory names to any client the CORS list admits;
         *     see spec §1's OPEN block on remote access.
         */
        get: operations["list_dirs"];
        put?: never;
        /** Creates one new directory to choose as a project's. */
        post: operations["create_dir"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This document. */
        get: operations["serve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stops a turn: terminates its process tree, confirms it is gone, and only
         *     then records it `Cancelled` (spec §2.3). Answers with the operation as it
         *     now stands — which may still be `Running` for a moment when the turn had
         *     already ended on its own and its ending is being recorded.
         * @description If the tree cannot be terminated the answer is 500
         *     `PROCESS_TERMINATION_FAILED`, and the operation is not `Cancelled`.
         */
        post: operations["stop_turn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every project, oldest first. */
        get: operations["list_projects"];
        put?: never;
        /** Creates a project owning an existing directory. */
        post: operations["create_project"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A project's planning threads, oldest first. An unknown project has none. */
        get: operations["list_threads"];
        put?: never;
        /** Creates a planning thread in a project. */
        post: operations["create_thread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Spec §2.10: durable replay, then a no-gap handoff to live, then
         *     de-duplication by durable sequence.
         * @description Two live sources, both taken BEFORE a single journal row is read:
         *
         *     - the storage's committed-sequence signal (spec §2.4: raised after each
         *       commit that appended to the journal). A commit that lands while the
         *       replay is being read shows up as a pending change, so it cannot fall into
         *       the gap between the replay's last read and the live phase.
         *     - the transient bus, for what is never stored: deltas, turn ends, meta.
         *
         *     Durable events reach the client only by reading the journal after
         *     `last_seq` — in the replay, and again on every signal change in the live
         *     phase — so each one is sent once, in sequence order, and de-duplication by
         *     `seq` is structural rather than left to the client. The bus's `Entry` items
         *     are therefore not forwarded: the same entry arrives as its durable
         *     `ThreadEntryAppended` event. Bus items for another thread are dropped.
         */
        get: operations["subscribe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{id}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A thread's entries in ordinal order. */
        get: operations["list_entries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{id}/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A thread's operations — its turns — newest first, each as it now stands.
         *     A client opening a thread reads this to learn whether a turn is running and
         *     which one (so it can offer Stop), then follows it on `/api/subscribe`,
         *     whose durable frames name their `operation_id`.
         */
        get: operations["list_operations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Starts a Planner turn. The turn runs in the thread's project directory and
         *     continues the thread's harness session; neither is the client's to name.
         * @description Spec §3.3: a long-running command answers 202 with an operation id, and the
         *     operation reaches its terminal outcome later — watch it on
         *     `/api/subscribe`. A turn that cannot run (no project directory, no harness)
         *     is still 202: the operation fails at `Prepare`, durably, with its reason.
         *
         *     A daemon that has begun to stop refuses the turn with 503 (spec §8.5).
         */
        post: operations["start_turn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Actor: {
            id: string;
            kind: string;
        };
        CreateDir: {
            /** @description One new path component that Windows would accept. */
            name: string;
            /** @description Absolute path to an existing directory. */
            parent: string;
        };
        CreateProject: {
            /**
             * @description The idempotency key (spec §3.2). The same id with the same request
             *     replays the first answer; with a different one it is a conflict.
             */
            command_id: string;
            /**
             * @description Absolute path to an existing directory, in any spelling; it is stored
             *     and returned canonical.
             */
            directory: string;
            name: string;
            slug: string;
        };
        CreateThread: {
            /** @description The idempotency key (spec §3.2), scoped to the project. */
            command_id: string;
            title: string;
        };
        /** @description One directory a person could open or choose. */
        DirectoryEntry: {
            /**
             * @description Hidden or system on Windows, or named with a leading dot. Flagged rather
             *     than filtered, so the client decides what to show and nothing is
             *     withheld without anyone saying so.
             */
            hidden: boolean;
            name: string;
            /** @description Absolute and canonical; sending it back names exactly this directory. */
            path: string;
        };
        /** @description A directory's immediate subdirectories, or the roots when `path` is `None`. */
        DirectoryListing: {
            /**
             * @description Sorted case-insensitively by name, which is how a person scans a list
             *     of folders; ties are broken by the exact name so the order is total.
             */
            entries: components["schemas"]["DirectoryEntry"][];
            /** @description Where "up" leads. `None` at a root, and for the roots themselves. */
            parent?: string | null;
            /** @description The directory listed, canonical. `None` for the roots. */
            path?: string | null;
        };
        EntryRef: {
            /**
             * @description Typed, because `operation/` exists. The three below reference entities
             *     whose modules Milestone 0 never creates, and §4.1's rule is that no module
             *     is created before the task that fills it.
             */
            Operation: components["schemas"]["OperationId"];
        } | {
            Decision: string;
        } | {
            Research: string;
        } | {
            Workflow: string;
        };
        /**
         * @description The body of every error this API answers with itself: the stable code a
         *     client matches on (spec §3.4), and a human message nobody should match on.
         *     A request axum rejects before a handler runs (malformed JSON, a missing
         *     query parameter) is answered by axum in plain text, not with this.
         */
        ErrorBody: {
            code: components["schemas"]["ErrorCode"];
            message: string;
        };
        /**
         * @description Stable codes clients pattern-match on. Never match on human text.
         *     Spec §3.4. `Blocked`/`Rejected` are domain outcomes and never appear here.
         * @enum {string}
         */
        ErrorCode: "PROCESS_SPAWN_FAILED" | "PROCESS_TERMINATED" | "PROCESS_TERMINATION_FAILED" | "RUNTIME_STOPPING" | "STORAGE_UNAVAILABLE" | "STORAGE_MIGRATION_FAILED" | "STORAGE_CONSTRAINT_VIOLATION" | "COMMAND_CONFLICT" | "IDEMPOTENCY_KEY_REQUIRED" | "INVALID_COMMAND" | "INVALID_CURSOR" | "AGENT_AUTH_FAILED" | "AGENT_UNSUPPORTED_PROFILE" | "PATH_INVALID" | "PATH_NOT_FOUND" | "PATH_NOT_A_DIRECTORY" | "PATH_ACCESS_DENIED" | "PATH_ALREADY_EXISTS" | "PATH_UNAVAILABLE";
        /**
         * @description Spec §2.7, §6.14. `thread_id` stays a plain `String` here on purpose: the
         *     `ProjectId`/`ThreadId`/`ThreadEntryId` sweep is a separate change, staged
         *     for reviewability, that follows this task (spec §4.1 OPEN block).
         */
        Operation: {
            cancel_requested_at?: string | null;
            created_at: string;
            failure_reason?: string | null;
            failure_stage?: string | null;
            finished_at?: string | null;
            id: components["schemas"]["OperationId"];
            interrupt_reason?: string | null;
            kind: string;
            outcome_json?: string | null;
            runtime_instance_id: components["schemas"]["RuntimeInstanceId"];
            started_at?: string | null;
            status_kind: string;
            thread_id?: string | null;
        };
        /** Format: uuid */
        OperationId: string;
        PlanningThread: {
            created_at: string;
            id: components["schemas"]["ThreadId"];
            project_id: components["schemas"]["ProjectId"];
            status: string;
            title: string;
        };
        Project: {
            created_at: string;
            /**
             * @description Spec §4.2: the directory this project's turns run in, as
             *     [`ProjectDirectory`] resolved it. `None` only for a project created
             *     before projects owned one (`migrations/0003_project_directory.sql`);
             *     a turn on such a project fails at Prepare rather than running in the
             *     daemon's own working directory.
             */
            directory?: string | null;
            id: components["schemas"]["ProjectId"];
            name: string;
            slug: string;
        };
        /** Format: uuid */
        ProjectId: string;
        /** Format: uuid */
        RuntimeInstanceId: string;
        StartTurn: {
            prompt: string;
        };
        ThreadEntry: {
            /**
             * @description Spec §4.2 calls this field's type `Principal`. Milestone 0 uses
             *     `events::Actor`, which already has exactly this shape (`kind` + `id`) and
             *     already answers "who did this" for durable events. Declaring a second
             *     identical struct would record one decision twice, which this project's
             *     documentation rules forbid. See the note in §4.2.
             */
            author: components["schemas"]["Actor"];
            body: string;
            created_at: string;
            id: components["schemas"]["ThreadEntryId"];
            kind: string;
            /** Format: int64 */
            ordinal: number;
            refs: components["schemas"]["EntryRef"][];
            thread_id: components["schemas"]["ThreadId"];
        };
        /** Format: uuid */
        ThreadEntryId: string;
        /** Format: uuid */
        ThreadId: string;
        TurnStarted: {
            operation_id: components["schemas"]["OperationId"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_dirs: {
        parameters: {
            query?: {
                /** @description Absolute path to list. Absent or empty: the roots to start from. */
                path?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryListing"];
                };
            };
            /** @description PATH_INVALID, PATH_NOT_A_DIRECTORY */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description PATH_ACCESS_DENIED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description PATH_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description PATH_UNAVAILABLE */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_dir: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDir"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryEntry"];
                };
            };
            /** @description PATH_INVALID, PATH_NOT_A_DIRECTORY */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description PATH_ACCESS_DENIED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description PATH_NOT_FOUND: no such parent */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description PATH_ALREADY_EXISTS */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description PATH_UNAVAILABLE */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    serve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description This OpenAPI document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    stop_turn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The turn's operation */
                id: components["schemas"]["OperationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"];
                };
            };
            /** @description INVALID_COMMAND: no such operation */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description STORAGE_CONSTRAINT_VIOLATION: it had already ended another way */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description PROCESS_TERMINATION_FAILED: the tree is still running, or STORAGE_UNAVAILABLE */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_projects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
            /** @description STORAGE_UNAVAILABLE */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_project: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProject"];
            };
        };
        responses: {
            /** @description Created, or the replay of the same command */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description PATH_INVALID, PATH_NOT_A_DIRECTORY */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description PATH_ACCESS_DENIED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description PATH_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description COMMAND_CONFLICT */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description STORAGE_UNAVAILABLE, PATH_UNAVAILABLE */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_threads: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project */
                id: components["schemas"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanningThread"][];
                };
            };
            /** @description STORAGE_UNAVAILABLE */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_thread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project */
                id: components["schemas"]["ProjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateThread"];
            };
        };
        responses: {
            /** @description Created, or the replay of the same command */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanningThread"];
                };
            };
            /** @description COMMAND_CONFLICT */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description STORAGE_UNAVAILABLE */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    subscribe: {
        parameters: {
            query: {
                /** @description The thread to watch. */
                thread_id: components["schemas"]["ThreadId"];
                /**
                 * @description The last durable sequence this client has already applied; 0 replays
                 *     the thread from its start.
                 */
                after?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Server-sent events for one thread (spec §2.10): the durable journal after `after`, then `caught-up`, then live. Each frame's `event:` names its kind and its `data:` is JSON unless stated.
             *
             *     - `durable` — `{seq, kind, operation_id, thread_id, payload}`: one journal event. `operation_id` and `thread_id` are the ids it names, `null` where it names none; `payload` is the event's JSON object. Sent once each, in `seq` order, in the replay and live alike; remember the highest `seq` and resubscribe with it as `after`.
             *     - `caught-up` — `{seq}`: the last replayed `seq`. The replay is over.
             *     - `delta` — `{op, text}`: streamed text of a running turn. Transient: never replayed.
             *     - `turn-end` — `{op, subtype, stop_reason}`: the harness finished a turn. Transient.
             *     - `meta` — `{op, label}`: any other harness line, by label. Transient.
             *     - `lagged` — empty: this client fell behind and transient frames were dropped; durable ones were not.
             *     - `fatal` — data is a message as plain text: the journal could not be read and the stream ends.
             *
             *     The stream also ends when the daemon stops. Reconnect with the last `seq`.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    list_entries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The thread */
                id: components["schemas"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadEntry"][];
                };
            };
            /** @description STORAGE_UNAVAILABLE */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_operations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The thread */
                id: components["schemas"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"][];
                };
            };
            /** @description STORAGE_UNAVAILABLE */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    start_turn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The thread */
                id: components["schemas"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartTurn"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnStarted"];
                };
            };
            /** @description INVALID_COMMAND: no such thread */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description STORAGE_UNAVAILABLE */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description RUNTIME_STOPPING: the daemon is shutting down */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
