//! One job: turn a scanned declaration list into the inventory document.
//!
//! Signatures are printed by `prettyplease`, never assembled by hand, and
//! functions are then collapsed onto one line each so the document reads like a
//! header file. Deliberately absent: line numbers. A line number is wrong the
//! moment a line is inserted above it, nothing in the build fails when it lies,
//! and one field that rots silently costs the reader their trust in every other
//! field beside it.

use crate::scan::{Decl, FileEntry};

pub const BANNER: &str = "<!-- GENERATED by crates/shadows/tests/codemap. Do not edit by hand. -->";

pub fn document(entries: &[FileEntry]) -> String {
    let mut out = String::new();
    out.push_str("# Code inventory\n\n");
    out.push_str(BANNER);
    out.push_str(
        "\n\nEvery declaration in each `crates/*/src` that something outside its own file\
         \ncan reach, with its full signature. Regenerate with:\n\n\
         ```bash\n\
         UPDATE_CODEMAP=1 cargo test -p shadows --test codemap\n\
         ```\n\n\
         `cargo test` fails when this file has drifted from the tree, so it cannot go\n\
         stale quietly. Attributes and doc comments are stripped: the source explains a\n\
         declaration, this file only says that it exists and what shape it has. What each\n\
         module *owns* is a judgement no generator can make — that lives in\n\
         [README.md](./README.md).\n\n",
    );

    // The entries arrive sorted by path, so each crate's files are contiguous and
    // one heading per crate groups them.
    let mut current_crate: Option<&str> = None;
    for entry in entries {
        let krate = entry.path.split('/').nth(1).unwrap_or("");
        if current_crate != Some(krate) {
            out.push_str(&format!("## Crate `{krate}`\n\n"));
            current_crate = Some(krate);
        }
        out.push_str(&format!("### `{}` — {} lines\n\n", entry.path, entry.lines));
        if entry.decls.is_empty() {
            out.push_str("Nothing reachable from outside this file.\n\n");
            continue;
        }

        out.push_str("```rust\n");
        let mut open_impl: Option<String> = None;
        for decl in &entry.decls {
            match decl {
                Decl::Free(item) => {
                    if open_impl.take().is_some() {
                        out.push_str("}\n\n");
                    }
                    out.push_str(&free_item(item));
                }
                Decl::Method { owner, vis, sig } => {
                    if open_impl.as_deref() != Some(owner.as_str()) {
                        if open_impl.is_some() {
                            out.push_str("}\n\n");
                        }
                        out.push_str(&format!("impl {owner} {{\n"));
                        open_impl = Some(owner.clone());
                    }
                    out.push_str(&format!("    {}\n", signature(vis, sig)));
                }
            }
        }
        if open_impl.is_some() {
            out.push_str("}\n");
        }
        out.push_str("```\n\n");
    }

    out
}

/// A function reduced to its signature: `prettyplease` is given an empty body,
/// and the `{}` it prints is cut back off.
fn signature(vis: &syn::Visibility, sig: &syn::Signature) -> String {
    let item = syn::Item::Fn(syn::ItemFn {
        attrs: Vec::new(),
        vis: vis.clone(),
        sig: sig.clone(),
        block: Box::new(syn::Block {
            brace_token: Default::default(),
            stmts: Vec::new(),
        }),
    });
    let printed = unparse(&item);
    let trimmed = printed.trim_end().trim_end_matches("{}").trim_end();
    one_line(trimmed)
}

fn free_item(item: &syn::Item) -> String {
    match item {
        syn::Item::Fn(f) => format!("{}\n", signature(&f.vis, &f.sig)),
        // Structs, enums and traits keep their shape across several lines. Their
        // members are the thing a caller gets wrong, and one line hides them.
        syn::Item::Struct(s) => {
            let (public, hidden) = split_fields(s);
            let text = unparse(&syn::Item::Struct(public));
            if hidden == 0 {
                text
            } else {
                format!(
                    "{text}// + {hidden} private field{}\n",
                    if hidden == 1 { "" } else { "s" }
                )
            }
        }
        syn::Item::Enum(e) => unparse(&syn::Item::Enum(e.clone())),
        syn::Item::Trait(t) => unparse(&syn::Item::Trait(t.clone())),
        other => format!("{}\n", one_line(unparse(other).trim_end())),
    }
}

/// Private fields are dropped rather than printed, because this document lists
/// what a caller can reach. Their count is still stated, so the struct is not
/// misread as having only these fields.
fn split_fields(s: &syn::ItemStruct) -> (syn::ItemStruct, usize) {
    let mut public = s.clone();
    let mut hidden = 0;
    if let syn::Fields::Named(named) = &mut public.fields {
        let before = named.named.len();
        let kept: Vec<_> = named
            .named
            .iter()
            .filter(|f| !matches!(f.vis, syn::Visibility::Inherited))
            .cloned()
            .collect();
        hidden = before - kept.len();
        named.named = kept.into_iter().collect();
    }
    (public, hidden)
}

fn unparse(item: &syn::Item) -> String {
    prettyplease::unparse(&syn::File {
        shebang: None,
        attrs: Vec::new(),
        items: vec![stripped(item)],
    })
}

/// Attributes and doc comments are removed before printing. The binding reason
/// is not brevity: a doc comment copied here is the same prose living in two
/// files, and this project's documentation rules forbid recording one thing
/// twice. Collapsing a declaration onto one line would also turn its doc
/// comment into unreadable run-on text.
fn stripped(item: &syn::Item) -> syn::Item {
    let mut item = item.clone();
    match &mut item {
        syn::Item::Struct(s) => {
            s.attrs.clear();
            for field in &mut s.fields {
                field.attrs.clear();
            }
        }
        syn::Item::Enum(e) => {
            e.attrs.clear();
            for variant in &mut e.variants {
                variant.attrs.clear();
                for field in &mut variant.fields {
                    field.attrs.clear();
                }
            }
        }
        syn::Item::Trait(t) => {
            t.attrs.clear();
            for member in &mut t.items {
                match member {
                    syn::TraitItem::Fn(f) => f.attrs.clear(),
                    syn::TraitItem::Type(ty) => ty.attrs.clear(),
                    syn::TraitItem::Const(c) => c.attrs.clear(),
                    _ => {}
                }
            }
        }
        syn::Item::Fn(f) => f.attrs.clear(),
        syn::Item::Type(t) => t.attrs.clear(),
        syn::Item::Const(c) => c.attrs.clear(),
        syn::Item::Static(s) => s.attrs.clear(),
        syn::Item::Use(u) => u.attrs.clear(),
        _ => {}
    }
    item
}

/// `prettyplease` wraps long signatures across lines. Joining them restores one
/// declaration per line; the whitespace fixes undo the wrap's own artefacts at
/// bracket and comma boundaries.
fn one_line(text: &str) -> String {
    let joined = text
        .lines()
        .map(str::trim)
        .filter(|l| !l.is_empty())
        .collect::<Vec<_>>()
        .join(" ");
    joined
        .replace("( ", "(")
        .replace(" )", ")")
        .replace(",)", ")")
}
